/**
 * Analyze an AST and extract top-level function delarations
 *
 * @param {object} ast - Abstract Syntax Tree (AST) generated by the parser
 * @returns {string[]} names of the functions found in the AST
 */
export function analyzeSource(ast) {
  const functions = [];

  ast.body.forEach((node) => {
    if (node.type === "FunctionDeclaration") {
      functions.push(node.id.name);
    }
  });

  return functions;
}
