/**
 * Analyze an AST and extract top-level function declarations
 *
 * @param {object} ast - Abstract Syntax Tree (AST) generated by the parser
 * @returns {object[]} functions with their names and parameters
 */
export function analyzeSource(ast) {
  const functions = [];

  ast.body.forEach((node) => {
    if (node.type === "FunctionDeclaration") {
      functions.push({
        name: node.id.name,
        parameters: node.params.map((param) => {
          return param.name;
        }),
      });
    }
  });

  return functions;
}
